version: '3.8'
services:
  web:
    build:
      context: ./
      target: production
    volumes:
      - .:/src
    command: npm run start:prod
    ports:
      - "3000:3000"
    env_file:
      - .env